# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Sun Sep 08 00:53:17 IST 2024

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design wallace

set_load -pin_load 0.15 [get_ports {out[63]}]
set_load -pin_load 0.15 [get_ports {out[62]}]
set_load -pin_load 0.15 [get_ports {out[61]}]
set_load -pin_load 0.15 [get_ports {out[60]}]
set_load -pin_load 0.15 [get_ports {out[59]}]
set_load -pin_load 0.15 [get_ports {out[58]}]
set_load -pin_load 0.15 [get_ports {out[57]}]
set_load -pin_load 0.15 [get_ports {out[56]}]
set_load -pin_load 0.15 [get_ports {out[55]}]
set_load -pin_load 0.15 [get_ports {out[54]}]
set_load -pin_load 0.15 [get_ports {out[53]}]
set_load -pin_load 0.15 [get_ports {out[52]}]
set_load -pin_load 0.15 [get_ports {out[51]}]
set_load -pin_load 0.15 [get_ports {out[50]}]
set_load -pin_load 0.15 [get_ports {out[49]}]
set_load -pin_load 0.15 [get_ports {out[48]}]
set_load -pin_load 0.15 [get_ports {out[47]}]
set_load -pin_load 0.15 [get_ports {out[46]}]
set_load -pin_load 0.15 [get_ports {out[45]}]
set_load -pin_load 0.15 [get_ports {out[44]}]
set_load -pin_load 0.15 [get_ports {out[43]}]
set_load -pin_load 0.15 [get_ports {out[42]}]
set_load -pin_load 0.15 [get_ports {out[41]}]
set_load -pin_load 0.15 [get_ports {out[40]}]
set_load -pin_load 0.15 [get_ports {out[39]}]
set_load -pin_load 0.15 [get_ports {out[38]}]
set_load -pin_load 0.15 [get_ports {out[37]}]
set_load -pin_load 0.15 [get_ports {out[36]}]
set_load -pin_load 0.15 [get_ports {out[35]}]
set_load -pin_load 0.15 [get_ports {out[34]}]
set_load -pin_load 0.15 [get_ports {out[33]}]
set_load -pin_load 0.15 [get_ports {out[32]}]
set_load -pin_load 0.15 [get_ports {out[31]}]
set_load -pin_load 0.15 [get_ports {out[30]}]
set_load -pin_load 0.15 [get_ports {out[29]}]
set_load -pin_load 0.15 [get_ports {out[28]}]
set_load -pin_load 0.15 [get_ports {out[27]}]
set_load -pin_load 0.15 [get_ports {out[26]}]
set_load -pin_load 0.15 [get_ports {out[25]}]
set_load -pin_load 0.15 [get_ports {out[24]}]
set_load -pin_load 0.15 [get_ports {out[23]}]
set_load -pin_load 0.15 [get_ports {out[22]}]
set_load -pin_load 0.15 [get_ports {out[21]}]
set_load -pin_load 0.15 [get_ports {out[20]}]
set_load -pin_load 0.15 [get_ports {out[19]}]
set_load -pin_load 0.15 [get_ports {out[18]}]
set_load -pin_load 0.15 [get_ports {out[17]}]
set_load -pin_load 0.15 [get_ports {out[16]}]
set_load -pin_load 0.15 [get_ports {out[15]}]
set_load -pin_load 0.15 [get_ports {out[14]}]
set_load -pin_load 0.15 [get_ports {out[13]}]
set_load -pin_load 0.15 [get_ports {out[12]}]
set_load -pin_load 0.15 [get_ports {out[11]}]
set_load -pin_load 0.15 [get_ports {out[10]}]
set_load -pin_load 0.15 [get_ports {out[9]}]
set_load -pin_load 0.15 [get_ports {out[8]}]
set_load -pin_load 0.15 [get_ports {out[7]}]
set_load -pin_load 0.15 [get_ports {out[6]}]
set_load -pin_load 0.15 [get_ports {out[5]}]
set_load -pin_load 0.15 [get_ports {out[4]}]
set_load -pin_load 0.15 [get_ports {out[3]}]
set_load -pin_load 0.15 [get_ports {out[2]}]
set_load -pin_load 0.15 [get_ports {out[1]}]
set_load -pin_load 0.15 [get_ports {out[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -add_delay -max 0.8 [get_ports {a[31]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[30]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[29]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[28]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[27]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[26]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[25]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[24]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[23]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[22]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[21]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[20]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[19]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[18]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[17]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[16]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[15]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[14]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[13]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[12]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[11]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[10]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[9]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[8]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[7]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[6]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[5]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[4]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[3]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[2]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[1]}]
set_input_delay -add_delay -max 0.8 [get_ports {a[0]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[31]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[30]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[29]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[28]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[27]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[26]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[25]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[24]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[23]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[22]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[21]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[20]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[19]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[18]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[17]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[16]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[15]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[14]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[13]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[12]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[11]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[10]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[9]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[8]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[7]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[6]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[5]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[4]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[3]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[2]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[1]}]
set_input_delay -add_delay -max 0.8 [get_ports {b[0]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[63]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[62]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[61]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[60]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[59]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[58]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[57]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[56]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[55]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[54]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[53]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[52]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[51]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[50]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[49]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[48]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[47]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[46]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[45]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[44]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[43]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[42]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[41]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[40]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[39]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[38]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[37]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[36]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[35]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[34]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[33]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[32]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[31]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[30]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[29]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[28]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[27]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[26]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[25]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[24]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[23]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[22]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[21]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[20]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[19]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[18]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[17]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[16]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[15]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[14]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[13]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[12]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[11]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[10]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[9]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[8]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[7]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[6]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[5]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[4]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[3]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[2]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[1]}]
set_output_delay -add_delay -max 0.8 [get_ports {out[0]}]
set_max_fanout 20.000 [current_design]
set_input_transition 0.12 [get_ports {a[31]}]
set_input_transition 0.12 [get_ports {a[30]}]
set_input_transition 0.12 [get_ports {a[29]}]
set_input_transition 0.12 [get_ports {a[28]}]
set_input_transition 0.12 [get_ports {a[27]}]
set_input_transition 0.12 [get_ports {a[26]}]
set_input_transition 0.12 [get_ports {a[25]}]
set_input_transition 0.12 [get_ports {a[24]}]
set_input_transition 0.12 [get_ports {a[23]}]
set_input_transition 0.12 [get_ports {a[22]}]
set_input_transition 0.12 [get_ports {a[21]}]
set_input_transition 0.12 [get_ports {a[20]}]
set_input_transition 0.12 [get_ports {a[19]}]
set_input_transition 0.12 [get_ports {a[18]}]
set_input_transition 0.12 [get_ports {a[17]}]
set_input_transition 0.12 [get_ports {a[16]}]
set_input_transition 0.12 [get_ports {a[15]}]
set_input_transition 0.12 [get_ports {a[14]}]
set_input_transition 0.12 [get_ports {a[13]}]
set_input_transition 0.12 [get_ports {a[12]}]
set_input_transition 0.12 [get_ports {a[11]}]
set_input_transition 0.12 [get_ports {a[10]}]
set_input_transition 0.12 [get_ports {a[9]}]
set_input_transition 0.12 [get_ports {a[8]}]
set_input_transition 0.12 [get_ports {a[7]}]
set_input_transition 0.12 [get_ports {a[6]}]
set_input_transition 0.12 [get_ports {a[5]}]
set_input_transition 0.12 [get_ports {a[4]}]
set_input_transition 0.12 [get_ports {a[3]}]
set_input_transition 0.12 [get_ports {a[2]}]
set_input_transition 0.12 [get_ports {a[1]}]
set_input_transition 0.12 [get_ports {a[0]}]
set_input_transition 0.12 [get_ports {b[31]}]
set_input_transition 0.12 [get_ports {b[30]}]
set_input_transition 0.12 [get_ports {b[29]}]
set_input_transition 0.12 [get_ports {b[28]}]
set_input_transition 0.12 [get_ports {b[27]}]
set_input_transition 0.12 [get_ports {b[26]}]
set_input_transition 0.12 [get_ports {b[25]}]
set_input_transition 0.12 [get_ports {b[24]}]
set_input_transition 0.12 [get_ports {b[23]}]
set_input_transition 0.12 [get_ports {b[22]}]
set_input_transition 0.12 [get_ports {b[21]}]
set_input_transition 0.12 [get_ports {b[20]}]
set_input_transition 0.12 [get_ports {b[19]}]
set_input_transition 0.12 [get_ports {b[18]}]
set_input_transition 0.12 [get_ports {b[17]}]
set_input_transition 0.12 [get_ports {b[16]}]
set_input_transition 0.12 [get_ports {b[15]}]
set_input_transition 0.12 [get_ports {b[14]}]
set_input_transition 0.12 [get_ports {b[13]}]
set_input_transition 0.12 [get_ports {b[12]}]
set_input_transition 0.12 [get_ports {b[11]}]
set_input_transition 0.12 [get_ports {b[10]}]
set_input_transition 0.12 [get_ports {b[9]}]
set_input_transition 0.12 [get_ports {b[8]}]
set_input_transition 0.12 [get_ports {b[7]}]
set_input_transition 0.12 [get_ports {b[6]}]
set_input_transition 0.12 [get_ports {b[5]}]
set_input_transition 0.12 [get_ports {b[4]}]
set_input_transition 0.12 [get_ports {b[3]}]
set_input_transition 0.12 [get_ports {b[2]}]
set_input_transition 0.12 [get_ports {b[1]}]
set_input_transition 0.12 [get_ports {b[0]}]
set_wire_load_mode "enclosed"
